name: UpdateLinks

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  updateLinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Update links
        run: python "versions\updateLinks.py"

